"""
Ideas de plantas nuevas para sumar y catálogo de huerta.
"""

NEW_IDEAS_FRENTE = [
    {"common": "Ceibo (Erythrina crista-galli)", "sci": "Erythrina crista-galli",
     "type": "Árbol pequeño caduco · NATIVA",
     "tags": ["nativa", "polinizadores", "aves", "ornamental"],
     "why": "🇺🇾 Árbol nacional de Uruguay y Argentina. Flores rojas espectaculares en racimos durante todo el verano. Atrae picaflores. Tolera sequía e inundación.",
     "where": "Pleno sol, junto al Aguaribay (F-8) — armarías un trío de nativas con guayabo + aguaribay + ceibo.",
     "size": "5-10m alt. × 4-6m diámetro",
     "season_plant": "Otoño-invierno (mayo-agosto)"},
    {"common": "Lavanda mariposa (Lavandula stoechas)", "sci": "Lavandula stoechas",
     "type": "Aromática perenne",
     "tags": ["aromatica", "polinizadores", "abejas"],
     "why": "Florece más tiempo que la dentata, espigas con 'orejitas' violáceas distintivas. Súper polinizadora. Hace de borde bajo perfecto.",
     "where": "Junto a F-5 como borde bajo del cantero, o repetir bajo el ciruelo F-4.",
     "size": "60-80cm × 60cm",
     "season_plant": "Otoño (abril-mayo) o primavera temprana (agosto-septiembre)"},
    {"common": "Salvia 'Hot Lips' (Salvia microphylla)", "sci": "Salvia microphylla",
     "type": "Arbusto perenne",
     "tags": ["aromatica", "polinizadores", "picaflor"],
     "why": "Flores bicolor blanco-rojo todo el año en Uruguay. Imán de picaflores. Hojas aromáticas a grosella. Resiste heladas.",
     "where": "En el cantero del frente, alternando con la abelia F-7 o como borde bajo del ciruelo F-4.",
     "size": "100cm × 100cm",
     "season_plant": "Primavera (septiembre-octubre)"},
    {"common": "Jazmín del país (Jasminum mesnyi)", "sci": "Jasminum mesnyi",
     "type": "Arbusto trepador semi-caduco",
     "tags": ["trepadora", "ornamental", "perfume"],
     "why": "Flores amarillas dobles abundantes en agosto-septiembre. Diferente al jazmín de leche. Excelente sobre cercos o muros.",
     "where": "Sobre el cerco junto a F-2 (Bignonia) — alternarían colores: rosa de bignonia, amarillo de jazmín.",
     "size": "3-4m largo · trepadora",
     "season_plant": "Otoño (abril-mayo)"},
    {"common": "Rosa Iceberg (Rosa 'Iceberg')", "sci": "Rosa × hybrida 'Iceberg'",
     "type": "Arbusto rosa floribunda",
     "tags": ["ornamental", "polinizadores"],
     "why": "Rosa más resistente y de más larga floración del mundo. Flores blanco puro casi todo el año en Uruguay. Pocas espinas, pocas enfermedades.",
     "where": "Como acento puntual en macetas grandes en el frente o trasplantada a tierra.",
     "size": "120cm × 100cm",
     "season_plant": "Junio-julio (raíz desnuda) o septiembre (en maceta)"},
    {"common": "Clavel del aire (Tillandsia spp.)", "sci": "Tillandsia spp.",
     "type": "Epífitas · NATIVAS",
     "tags": ["nativa", "ornamental", "epifita"],
     "why": "🇺🇾 Las hay nativas (T. aëranthos, T. usneoides). No necesitan tierra. Atan a ramas o cuerdas. Flores rojas/azules pequeñas.",
     "where": "Colgando de las palmeras pindó (B-21 sobre todo) o en el aguaribay F-8 cuando esté bien identificado.",
     "size": "Varía",
     "season_plant": "Cualquier época"},
    {"common": "Anís estrellado / Estragón (mezcla)", "sci": "Tagetes lucida",
     "type": "Aromática perenne",
     "tags": ["aromatica", "comestible", "polinizadores"],
     "why": "Falso estragón mexicano — sabor anisado intenso. Flores amarillas. Repele plagas. Resistente al frío.",
     "where": "Borde bajo del cantero del frente, junto a la lavanda existente.",
     "size": "50cm × 50cm",
     "season_plant": "Primavera (septiembre)"},
    {"common": "Aromo (Acacia caven)", "sci": "Vachellia caven",
     "type": "Árbol pequeño · NATIVO",
     "tags": ["nativa", "polinizadores", "aromatica"],
     "why": "🇺🇾 Espinillo nativo del Río de la Plata. Flores amarillas pompones perfumadísimas (julio-septiembre). Tolera sequía total.",
     "where": "Si hay espacio en una esquina del frente o como árbol aislado. Cuidado con espinas.",
     "size": "4-7m × 3m",
     "season_plant": "Otoño-invierno"},
]

NEW_IDEAS_FONDO = [
    {"common": "Ibirapitá (Peltophorum dubium)", "sci": "Peltophorum dubium",
     "type": "Árbol grande caduco · NATIVO",
     "tags": ["nativa", "polinizadores", "aves", "ornamental", "sombra"],
     "why": "🇺🇾 'Árbol de Artigas'. Flores amarillas en panículas espectaculares en diciembre-enero. Sombra fresca. Madera durísima.",
     "where": "Si hay espacio, esquina del fondo lejos de la pileta y de cables eléctricos. Reemplazo del liquidámbar si quieren más nativas.",
     "size": "15-25m × 12m",
     "season_plant": "Otoño (mayo-junio)"},
    {"common": "Higuera (Ficus carica)", "sci": "Ficus carica",
     "type": "Frutal caduco",
     "tags": ["frutal", "ornamental"],
     "why": "Higos negros y verdes desde diciembre a marzo. Hojas grandes ornamentales. Súper rústica, pocas enfermedades en Uruguay.",
     "where": "Cualquier rincón soleado del fondo. Cerca del corral o galpón.",
     "size": "3-5m × 4m",
     "season_plant": "Junio-julio (raíz desnuda)"},
    {"common": "Granado (Punica granatum)", "sci": "Punica granatum",
     "type": "Frutal caduco",
     "tags": ["frutal", "ornamental"],
     "why": "Flores rojo-anaranjadas tipo trompeta en primavera-verano. Granadas en otoño. Antioxidante. Hermoso ornamental aunque no se coma el fruto.",
     "where": "Junto al peral B-39 o limonero B-23 — ya tendrías un mini-orchard.",
     "size": "2-4m × 3m",
     "season_plant": "Junio-julio"},
    {"common": "Naranjo agrio (Citrus aurantium)", "sci": "Citrus × aurantium",
     "type": "Frutal perenne",
     "tags": ["frutal", "perfume", "polinizadores"],
     "why": "Para hacer mermelada amarga estilo inglés. Flor de azahar perfumadísima (la que más perfuma de los cítricos). Atrae mariposas Papilio.",
     "where": "Junto a B-23 (limonero) y B-24 (mandarino) — completar la huerta cítrica.",
     "size": "3-5m × 3m",
     "season_plant": "Septiembre-octubre"},
    {"common": "Jacarandá (Jacaranda mimosifolia)", "sci": "Jacaranda mimosifolia",
     "type": "Árbol grande semi-caduco",
     "tags": ["polinizadores", "ornamental", "sombra"],
     "why": "Florece azul-violáceo espectacular en noviembre-diciembre. Hojas tipo helecho elegantes. Originario de Argentina-Bolivia (regional).",
     "where": "Si hay espacio amplio, rincón del fondo. Lejos de la pileta (pétalos manchan).",
     "size": "10-15m × 8m",
     "season_plant": "Primavera (septiembre)"},
    {"common": "Camelia (Camellia japonica)", "sci": "Camellia japonica",
     "type": "Arbusto perenne",
     "tags": ["ornamental", "sombra"],
     "why": "Flores rosa, blancas o rojas dobles espectaculares de mayo a septiembre — cuando casi nada florece. Adora la sombra.",
     "where": "Bajo el liquidámbar B-37 o junto al jazmín B-3 en zona sombreada.",
     "size": "150cm × 100cm",
     "season_plant": "Marzo-abril o septiembre"},
    {"common": "Hibiscus tropical doble", "sci": "Hibiscus rosa-sinensis (variedades)",
     "type": "Arbusto perenne",
     "tags": ["ornamental", "polinizadores"],
     "why": "Variedades dobles y de colores: amarillo, salmón, fucsia. Combina con tu B-4 existente (que es naranja).",
     "where": "Junto al hibisco existente B-4 para hacer una colección de colores.",
     "size": "150-200cm",
     "season_plant": "Septiembre-octubre"},
    {"common": "Plumbago / Jazmín celeste (Plumbago auriculata)", "sci": "Plumbago auriculata",
     "type": "Arbusto semi-trepador",
     "tags": ["polinizadores", "mariposas", "ornamental"],
     "why": "Flores celestes pálidas todo el verano. Único arbusto azul resistente. Imán de mariposas.",
     "where": "Junto al cerco del fondo, contra el muro del vecino. Llenaría rincones vacíos.",
     "size": "150-200cm × 200cm",
     "season_plant": "Primavera (septiembre)"},
    {"common": "Salvia uliginosa", "sci": "Salvia uliginosa",
     "type": "Herbácea perenne · NATIVA",
     "tags": ["nativa", "polinizadores", "abejas"],
     "why": "🇺🇾 Salvia azul nativa de los humedales del Río de la Plata. Flores azul cielo todo el verano. Atrae mariposas y abejorros.",
     "where": "Borde bajo del cantero junto a la palmera B-21 o en zonas húmedas cerca de la pileta.",
     "size": "120cm × 60cm",
     "season_plant": "Otoño o primavera"},
    {"common": "Mburucuyá / Pasionaria (Passiflora caerulea)", "sci": "Passiflora caerulea",
     "type": "Trepadora perenne · NATIVA",
     "tags": ["nativa", "trepadora", "polinizadores", "frutal"],
     "why": "🇺🇾 Trepadora nativa con flores azul-blancas extraordinarias y frutos comestibles ('granadilla'). Súper polinizadora. Resistente a heladas.",
     "where": "Sobre el cerco del fondo o en una pérgola. Reemplazaría parte del jazmín B-3 si querés diversificar.",
     "size": "5-8m largo",
     "season_plant": "Otoño-primavera"},
]

HUERTA = [
    {"common": "Tomate", "sci": "Solanum lycopersicum",
     "type": "Hortaliza fruto · anual",
     "tags": ["huerta", "fruto", "verano"],
     "siembra": [8, 9, 10],
     "transplante": [10, 11, 12],
     "cosecha": [12, 1, 2, 3, 4],
     "tip": "Sembrar variedad 'Platense' o 'Cherry'. Tutorar desde el inicio. Despuntar chupones cada semana.",
     "sun": "Pleno sol", "water": "Diario en verano, profundo. Mejor en gotero."},
    {"common": "Lechuga", "sci": "Lactuca sativa",
     "type": "Hortaliza hoja · anual",
     "tags": ["huerta", "hoja", "todo-año"],
     "siembra": [3, 4, 5, 7, 8, 9, 10],
     "transplante": [4, 5, 6, 8, 9, 10, 11],
     "cosecha": [5, 6, 7, 8, 9, 10, 11, 12],
     "tip": "Sembrar cada 3 semanas para tener siempre. Mantillada, criolla, mantecosa. En verano va a la 'flor' rápido — preferir variedades resistentes al calor.",
     "sun": "Sol parcial — sombra mediodía en verano", "water": "Diario, riego suave"},
    {"common": "Acelga", "sci": "Beta vulgaris var. cicla",
     "type": "Hortaliza hoja · bienal",
     "tags": ["huerta", "hoja", "todo-año"],
     "siembra": [2, 3, 4, 8, 9, 10],
     "transplante": [3, 4, 5, 9, 10, 11],
     "cosecha": [5, 6, 7, 8, 9, 10, 11, 12, 1],
     "tip": "Cosechá hojas externas y dejá las del centro — produce 6-8 meses por planta.",
     "sun": "Sol o sol parcial", "water": "2-3×/semana"},
    {"common": "Rúcula", "sci": "Eruca vesicaria",
     "type": "Hortaliza hoja · anual",
     "tags": ["huerta", "hoja", "rapida"],
     "siembra": [3, 4, 5, 8, 9, 10],
     "transplante": [],
     "cosecha": [5, 6, 7, 8, 9, 10, 11, 12],
     "tip": "Lista en 30-40 días. Sembrar directo a chorrillo. Resiembra sola.",
     "sun": "Sol parcial", "water": "Diario, suave"},
    {"common": "Espinaca", "sci": "Spinacia oleracea",
     "type": "Hortaliza hoja · anual",
     "tags": ["huerta", "hoja", "invierno"],
     "siembra": [2, 3, 4, 5],
     "transplante": [],
     "cosecha": [5, 6, 7, 8, 9],
     "tip": "Verdura de invierno. Sembrar directo. No tolera calor — sólo otoño-invierno en Uruguay.",
     "sun": "Sol", "water": "Regular"},
    {"common": "Zapallito de tronco", "sci": "Cucurbita pepo",
     "type": "Hortaliza fruto · anual",
     "tags": ["huerta", "fruto", "verano"],
     "siembra": [9, 10, 11, 12],
     "transplante": [10, 11, 12, 1],
     "cosecha": [12, 1, 2, 3, 4],
     "tip": "Variedades 'tronco' compactas (no se extienden). Una planta da 15-20 zapallitos por temporada.",
     "sun": "Pleno sol", "water": "Profundo 3×/semana"},
    {"common": "Morrón / Pimiento", "sci": "Capsicum annuum",
     "type": "Hortaliza fruto · anual",
     "tags": ["huerta", "fruto", "verano"],
     "siembra": [8, 9],
     "transplante": [10, 11, 12],
     "cosecha": [1, 2, 3, 4, 5],
     "tip": "Sembrar en almácigo en agosto. Tutorar. Cosechar verde o esperar a que se pongan rojo/amarillo (más vitamina C).",
     "sun": "Pleno sol", "water": "Diario en verano"},
    {"common": "Cebolla", "sci": "Allium cepa",
     "type": "Hortaliza bulbo · bienal",
     "tags": ["huerta", "bulbo", "invierno"],
     "siembra": [3, 4, 5],
     "transplante": [6, 7, 8],
     "cosecha": [11, 12, 1],
     "tip": "Variedades 'Pera' o 'Valenciana'. Sembrar densa, ralear y trasplantar en invierno. Cosechar cuando se acuesta el follaje.",
     "sun": "Pleno sol", "water": "Regular pero no encharcar"},
    {"common": "Ajo", "sci": "Allium sativum",
     "type": "Hortaliza bulbo · anual",
     "tags": ["huerta", "bulbo", "invierno"],
     "siembra": [3, 4, 5, 6],
     "transplante": [],
     "cosecha": [11, 12],
     "tip": "Plantar diente con punta hacia arriba en abril-mayo. Cosechar cuando hojas estén 50% amarillas. Seca al sol antes de guardar.",
     "sun": "Pleno sol", "water": "Bajo — odia exceso"},
    {"common": "Zanahoria", "sci": "Daucus carota",
     "type": "Hortaliza raíz · bienal",
     "tags": ["huerta", "raiz", "todo-año"],
     "siembra": [2, 3, 4, 8, 9, 10],
     "transplante": [],
     "cosecha": [5, 6, 7, 11, 12, 1],
     "tip": "Sembrar directo y ralear (dejar 3cm entre plantitas). Suelo arenoso suelto profundo. Tarda 90-110 días.",
     "sun": "Sol", "water": "Regular"},
    {"common": "Frutilla", "sci": "Fragaria × ananassa",
     "type": "Frutal herbáceo · perenne",
     "tags": ["huerta", "fruta", "perenne"],
     "siembra": [],
     "transplante": [3, 4, 5],
     "cosecha": [10, 11, 12, 1],
     "tip": "Plantar en otoño. Renovar plantines cada 2-3 años (los hijos de los estolones). Mulch de paja para fruta limpia.",
     "sun": "Sol pleno", "water": "Diario en fructificación"},
    {"common": "Albahaca", "sci": "Ocimum basilicum",
     "type": "Aromática anual",
     "tags": ["huerta", "aromatica", "verano"],
     "siembra": [9, 10, 11],
     "transplante": [10, 11, 12],
     "cosecha": [11, 12, 1, 2, 3, 4],
     "tip": "Pinchar las flores cuando aparecen — alarga la cosecha. Asociar con tomate (compañera ideal). No resiste heladas.",
     "sun": "Sol", "water": "Diario en verano"},
    {"common": "Perejil", "sci": "Petroselinum crispum",
     "type": "Aromática bienal",
     "tags": ["huerta", "aromatica", "todo-año"],
     "siembra": [2, 3, 8, 9, 10],
     "transplante": [],
     "cosecha": [5, 6, 7, 8, 9, 10, 11, 12, 1],
     "tip": "Tarda 3 semanas en germinar — paciencia. En el 2° año florece y termina su ciclo. Sembrar fresco cada año.",
     "sun": "Sol parcial", "water": "Regular"},
    {"common": "Cilantro", "sci": "Coriandrum sativum",
     "type": "Aromática anual",
     "tags": ["huerta", "aromatica", "rapida"],
     "siembra": [3, 4, 5, 8, 9, 10],
     "transplante": [],
     "cosecha": [5, 6, 7, 8, 9, 10, 11],
     "tip": "Lista en 60 días. Va a flor con calor — sembrar otoño/invierno o primaveras frías. Atrae sírfidos beneficiosos.",
     "sun": "Sol parcial en verano", "water": "Regular"},
    {"common": "Menta", "sci": "Mentha spicata",
     "type": "Aromática perenne",
     "tags": ["huerta", "aromatica", "perenne", "polinizadores"],
     "siembra": [],
     "transplante": [3, 4, 5, 8, 9, 10],
     "cosecha": [10, 11, 12, 1, 2, 3, 4, 5],
     "tip": "INVASORA — plantarla SIEMPRE en maceta o cantero contenido. Hace estolones que se apoderan del jardín.",
     "sun": "Sol parcial", "water": "Regular — humedad constante"},
]

HUERTA_LOCATION_IDEAS = [
    {"title": "🌞 Cantero soleado dedicado en el fondo",
     "desc": "Lo más recomendado: 4-6m² de tierra removida + abonada en una zona con sol pleno (mín. 6h). Cerca de la pileta o atrás del galpón. Permite rotación de cultivos y máxima productividad.",
     "pros": "Mejor productividad, fácil mantenimiento, espacio para todo: tomate, morrón, zapallitos, lechuga, etc.",
     "cons": "Hay que preparar la tierra inicial (cavar, abonar). Inversión inicial.",
     "best_for": "Quien quiere autosustentabilidad real, recomendado para el perfil 'medio' del usuario."},
    {"title": "📏 Cama elevada (raised bed)",
     "desc": "Cajón de madera de 1×3m, 30cm alto, lleno de tierra y compost. Más práctico para cuidar (no agacharse). Listo para sembrar de inmediato.",
     "pros": "No depende del suelo existente, drenaje perfecto, cómodo para trabajar, decorativo.",
     "cons": "Costo inicial mayor, riego más frecuente (calor más intenso).",
     "best_for": "Si la tierra del fondo es muy compacta o tiene raíces de árboles que compiten."},
    {"title": "🪴 Macetones grandes en la zona soleada",
     "desc": "5-8 macetones de 50L+ con tomate, morrón, lechuga, aromáticas. En la zona del frente cocina o cerca de la pileta donde haya sol.",
     "pros": "Movible, sin obras, control total del sustrato. Bueno para empezar.",
     "cons": "Volumen limitado, requieren más riego, no permite cultivos grandes (zapallo, etc).",
     "best_for": "Probar la huerta sin compromiso, antes de decidir un espacio fijo."},
    {"title": "🌿 Aromáticas integradas en el jardín actual",
     "desc": "Romero, lavanda, menta, perejil, cilantro entre las plantas existentes — sin armar una huerta separada. Aprovechás los espacios libres.",
     "pros": "Sin obra, embellece, polinizadores. Ya tienen romero y lavanda — se amplía.",
     "cons": "Sólo aromáticas/condimentos, no permite huerta clásica.",
     "best_for": "Si quieren cocinar con condimentos frescos sin compromiso huerta."},
]

# ============================================================
# CONTACTOS WhatsApp por defecto (el usuario los puede editar en la UI)
# ============================================================
DEFAULT_CONTACTS = [
    {"id": "sofi", "name": "Sofi", "icon": "💚", "phone": "+59899516634",
     "default_template": "Hola Sofi! Tengo esta tarea pendiente del jardín:\n\n📌 \"{task}\"\n\nMás info acá: {link}"},
    {"id": "jardinero", "name": "Jardinero", "icon": "🌿", "phone": "",
     "default_template": "Hola! Necesito ayuda con una tarea de jardinería en casa: \"{task}\".\n\nDetalle acá: {link}\n\n¿Cuándo podrías venir? Saludos."},
    {"id": "jornalero", "name": "Jornalero multiuso", "icon": "🛠️", "phone": "",
     "default_template": "Hola! Tengo una tarea para hacer en casa: \"{task}\".\n\nMás info: {link}\n\n¿Tendrías disponibilidad esta semana? Gracias."},
    {"id": "piscina", "name": "Empresa de piscina", "icon": "🏊", "phone": "",
     "default_template": "Hola! Necesitaría coordinar un servicio de piscina relacionado con: \"{task}\".\n\n{link}\n\n¿Cuándo podrían pasar?"},
    {"id": "electricista", "name": "Electricista", "icon": "⚡", "phone": "",
     "default_template": "Hola! Necesito un electricista para: \"{task}\".\n\n{link}\n\n¿Tendrías disponibilidad?"},
    {"id": "vivero", "name": "Vivero / Plantas", "icon": "🌱", "phone": "",
     "default_template": "Hola! Quería consultar sobre: \"{task}\".\n\n{link}\n\n¿Tienen disponibilidad?"},
    {"id": "leniador", "name": "Leñador / Podador", "icon": "🪓", "phone": "",
     "default_template": "Hola! Necesito un servicio de poda/extracción: \"{task}\".\n\n{link}\n\n¿Cuándo podrías venir a evaluar?"},
]
