"""
Catálogo de plantas del jardín Pacha Mama.
Cada planta tiene su info, calendario, urgencia y tags.
"""

PLANTS = [
    # ===== FRENTE =====
    {
        "id_codes": ["F-1"], "zone": "frente",
        "common": "Guayabo del país",
        "charrua": "Ñunde (charrúa) / Arasá-pé (guaraní)",
        "sci": "Acca sellowiana",
        "other_names": "Feijoa, guayaba serrana, guayabo verde",
        "desc": "Árbol-arbusto NATIVO uruguayo. Hojas perennes color verde-grisáceo plateado por debajo. Flores blancas y rojas comestibles en primavera, frutos verdes ovalados aromáticos a fin de verano.",
        "type": "perenne",
        "fun_fact": "Sus pétalos son comestibles y dulces — en Uruguay y Brasil se comían como golosina por niños. El fruto es uno de los pocos cítricos-aromáticos nativos del Río de la Plata.",
        "prune_when": "Junio a agosto (invierno) tras cosecha. Evitar podar en floración.",
        "prune_how": "Ligera (10-20%). Eliminar ramas cruzadas, secas y chupones. Mantener forma natural.",
        "water": "Bajo. 1×/semana en verano, casi nada en invierno. Tolera sequía cuando establecido.",
        "light": "Pleno sol",
        "tags": ["nativa", "frutal", "polinizadores", "aves", "ornamental"],
        "loc_photo": "FrenteCasa_MiradoCalle.jpg",
        "main_photo": "PXL_20260428_131301030_MP.webp",
        "flowering": [10, 11, 12],
        "fruiting": [3, 4, 5],
        "pruning": [6, 7, 8],
        "urgency": None,
    },
    {
        "id_codes": ["F-2"], "zone": "frente",
        "common": "Bignonia rosada / Podranea",
        "charrua": "",
        "sci": "Podranea ricasoliana",
        "other_names": "Bignonia rosa, jazmín de Zanzíbar",
        "desc": "Trepadora vigorosa de hojas pinadas brillantes y racimos de flores rosa-trompeta de mayo a verano. Crece rápido y cubre cercos enteros.",
        "type": "semi-perenne",
        "fun_fact": "Aunque la llamamos 'bignonia', no pertenece al género Bignonia sino a Podranea — fue separada en 1980 por su tubo floral curvo y semillas distintas.",
        "prune_when": "Junio-julio (poda fuerte de invierno) y agosto (formación pre-brotación).",
        "prune_how": "Severa (40-60%). Cortar ramas viejas y guías largas, dejar 3-4 yemas vigorosas por rama.",
        "water": "Medio. 2×/semana en verano, semanal el resto.",
        "light": "Pleno sol",
        "tags": ["exotica", "trepadora", "ornamental", "polinizadores"],
        "loc_photo": "FrenteCasa_MiradoCalle.jpg",
        "main_photo": "PXL_20260428_131311714_MP.webp",
        "flowering": [11, 12, 1, 2, 3, 4],
        "fruiting": [],
        "pruning": [6, 7, 8],
        "urgency": {"priority": "media", "action": "Poda fuerte de invierno", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["F-3", "F-6"], "zone": "frente",
        "common": "Fotinia",
        "charrua": "",
        "sci": "Photinia × fraseri",
        "other_names": "Photinia 'Red Robin'",
        "desc": "Arbusto perenne usado como cerco. Brotes rojo-coral espectaculares en primavera que viran a verde brillante. Pequeñas flores blancas en panículas en primavera.",
        "type": "perenne",
        "fun_fact": "Es un híbrido entre Photinia glabra y Photinia serrulata creado en Alabama en 1940 por Robert Fraser. El color rojo de los brotes es defensa contra herbívoros.",
        "prune_when": "Septiembre y febrero (después de cada brote). En cercos, recortar al menos 3 veces al año.",
        "prune_how": "Moderada (20-30%). Recortar todos los brotes para forzar nuevo brote rojo. Forma topiaria.",
        "water": "Medio. Semanal en verano, cada 10-15 días el resto.",
        "light": "Sol o sombra parcial",
        "tags": ["exotica", "ornamental", "cerco-vivo"],
        "loc_photo": "FrenteCasa_MirandoVecino.jpg",
        "main_photo": "PXL_20260428_131345511_MP.webp",
        "flowering": [10, 11],
        "fruiting": [],
        "pruning": [9, 2],
        "urgency": None,
    },
    {
        "id_codes": ["F-4"], "zone": "frente",
        "common": "Ciruelo de jardín",
        "charrua": "",
        "sci": "Prunus cerasifera 'Pissardii'",
        "other_names": "Ciruelo japonés, ciruelo púrpura, mirabolano",
        "desc": "Árbol caduco ornamental con hojas púrpuras intensas en primavera-verano. Flores rosadas suaves antes que las hojas (agosto). Frutos comestibles pero ácidos.",
        "type": "caduco",
        "fun_fact": "Lo trajo desde Persia el horticultor francés Pissard en 1880 — todos los ciruelos púrpura del mundo descienden de ese único ejemplar original.",
        "prune_when": "Junio a julio (plena dormancia). Después de la caída de hojas.",
        "prune_how": "Moderada (25-35%). Eliminar chupones, ramas cruzadas y guías largas. Mantener silueta abierta.",
        "water": "Medio. 2×/semana en verano, semanal en primavera-otoño.",
        "light": "Pleno sol (para máximo color púrpura)",
        "tags": ["exotica", "frutal", "ornamental"],
        "loc_photo": "FrenteCasa_MirandoVecino.jpg",
        "main_photo": "PXL_20260428_131325763_MP.webp",
        "flowering": [8, 9],
        "fruiting": [12, 1],
        "pruning": [6, 7],
        "urgency": {"priority": "alta", "action": "Poda invernal", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["F-5"], "zone": "frente",
        "common": "Coronita de novia (?)",
        "charrua": "",
        "sci": "Spiraea cantoniensis (a confirmar)",
        "other_names": "Espirea, novia",
        "desc": "Arbusto bajo con hojas pequeñas grisáceas. Pendiente confirmación. Si es coronita de novia, tira ramas arqueadas con flores blancas en cascada en primavera.",
        "type": "caduco",
        "fun_fact": "Si se confirma como Spiraea, su nombre 'coronita de novia' viene del uso popular de las ramas floridas para tocados nupciales en Europa del siglo XIX.",
        "prune_when": "Después de floración (octubre-noviembre).",
        "prune_how": "Moderada (30%). Cortar ramas viejas a ras de suelo para renovar.",
        "water": "Medio. Semanal en verano.",
        "light": "Pleno sol",
        "tags": ["exotica", "ornamental", "pendiente"],
        "loc_photo": "FrenteCasa_MirandoVecino.jpg",
        "main_photo": "PXL_20260428_131336459_MP.webp",
        "flowering": [10, 11],
        "fruiting": [],
        "pruning": [11, 12],
        "urgency": None,
    },
    {
        "id_codes": ["F-7"], "zone": "frente",
        "common": "Abelia",
        "charrua": "",
        "sci": "Abelia × grandiflora",
        "other_names": "Abelia chinesa",
        "desc": "Arbusto semi-perenne con flores blanco-rosadas tubulares pequeñas que duran de noviembre a mayo (¡muy larga floración!). Atrae mariposas y abejas.",
        "type": "semi-perenne",
        "fun_fact": "Su nombre honra al cirujano-botánico inglés Clarke Abel, que la encontró en China en 1817 durante una expedición diplomática. Su barco naufragó al volver — la planta sobrevivió pero las semillas se perdieron.",
        "prune_when": "Agosto-septiembre (antes del brote primaveral).",
        "prune_how": "Moderada (25-30%). Recortar tercio superior, eliminar ramas viejas.",
        "water": "Medio-bajo. Semanal en verano, cada 10-15 días el resto.",
        "light": "Pleno sol o sol parcial",
        "tags": ["exotica", "ornamental", "polinizadores", "mariposas"],
        "loc_photo": "FrenteCasa_MirandoVecino.jpg",
        "main_photo": "PXL_20260428_131358749_MP.webp",
        "flowering": [11, 12, 1, 2, 3, 4, 5],
        "fruiting": [],
        "pruning": [8, 9],
        "urgency": None,
    },
    {
        "id_codes": ["F-8"], "zone": "frente",
        "common": "Aguaribay / Molle",
        "charrua": "Aguaraibá (guaraní) / Molle (charrúa)",
        "sci": "Schinus molle",
        "other_names": "Falso pimentero, molle hediondo, terebinto del Perú",
        "desc": "Árbol NATIVO de copa amplia y ramas péndulas. Hojas perennes pinadas aromáticas. Frutos pequeños rosa-rojizos en racimos colgantes — son la 'pimienta rosa' de los gourmets.",
        "type": "perenne",
        "fun_fact": "Los Incas y guaraníes lo consideraban sagrado. Los frutos rosados son la verdadera 'pimienta rosa' que se vende en delicatessen — no son de pimentero verdadero. Sus hojas repelen mosquitos.",
        "prune_when": "Junio-julio (invierno). Solo formación y limpieza.",
        "prune_how": "Mínima (5-10%). Eliminar ramas secas, cruzadas o que rocen estructuras. Respetar forma péndula natural.",
        "water": "Muy bajo. Tolera sequía extrema una vez establecido.",
        "light": "Pleno sol",
        "tags": ["nativa", "polinizadores", "aves", "aromatica", "ornamental"],
        "loc_photo": "",
        "main_photo": "PXL_20260428_131445630_MP.webp",
        "flowering": [11, 12, 1],
        "fruiting": [3, 4, 5, 6],
        "pruning": [6, 7],
        "urgency": {"priority": "baja", "action": "Sacar foto numerada en panorámico del frente", "when": "Cuando puedan", "due_month": 8, "due_year": 2026},
    },

    # ===== FONDO =====
    {
        "id_codes": ["B-1"], "zone": "fondo",
        "common": "Santa Rita / Buganvilia",
        "charrua": "",
        "sci": "Bougainvillea spectabilis",
        "other_names": "Veranera, buganvilla, primavera",
        "desc": "Trepadora vigorosa con espinas y 'flores' fucsia-violáceas (en realidad son brácteas que envuelven la flor verdadera, blanca y minúscula). Floración explosiva en verano.",
        "type": "semi-perenne",
        "fun_fact": "La descubrió Jeanne Baret en 1768 — la primera mujer en circunnavegar el mundo, viajaba disfrazada de hombre en la expedición del almirante francés Bougainville. Le pusieron el nombre del capitán, no de ella. Recién en 2012 le dedicaron una variedad: 'Jeanne'.",
        "prune_when": "Agosto (antes del brote) y poda ligera post-floración (abril).",
        "prune_how": "Moderada-severa (30-50%). Reducir guías largas. Florece en madera nueva.",
        "water": "Bajo. La sequía estimula la floración. 1×/semana en verano, casi nada en invierno.",
        "light": "Pleno sol pleno (mín. 6h)",
        "tags": ["exotica", "trepadora", "ornamental", "polinizadores"],
        "loc_photo": "FondoCasa_FrenteDormitorio.jpg",
        "main_photo": "PXL_20260428_130048026_MP.webp",
        "flowering": [11, 12, 1, 2, 3],
        "fruiting": [],
        "pruning": [4, 8],
        "urgency": None,
    },
    {
        "id_codes": ["B-2"], "zone": "fondo",
        "common": "Pendiente identificación (¿algún jazmín?)",
        "charrua": "",
        "sci": "(a determinar)",
        "other_names": "—",
        "desc": "Arbusto redondeado con hojas brillantes. Pendiente. Necesita más fotos en floración.",
        "type": "perenne",
        "fun_fact": "—",
        "prune_when": "A determinar tras identificación",
        "prune_how": "—",
        "water": "Medio (provisional)",
        "light": "Sol parcial (provisional)",
        "tags": ["pendiente"],
        "loc_photo": "FondoCasa_FrenteDormitorio.jpg",
        "main_photo": "PXL_20260428_130056467_MP.webp",
        "flowering": [],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "baja", "action": "Sacar foto en floración para identificar", "when": "Primavera-verano 2026", "due_month": 10, "due_year": 2026},
    },
    {
        "id_codes": ["B-3"], "zone": "fondo",
        "common": "Jazmín de leche / estrellado",
        "charrua": "",
        "sci": "Trachelospermum jasminoides",
        "other_names": "Falso jazmín, jazmín chino, jazmín estrellado",
        "desc": "Trepadora perenne de hojas brillantes y flores blancas estrelladas extremadamente perfumadas (octubre-diciembre). Cubre techos y pérgolas en pocos años.",
        "type": "perenne",
        "fun_fact": "No es un verdadero jazmín (Jasminum) sino una apocinácea — pariente lejano de la adelfa. Su látex blanco al cortar la rama es tóxico, pero la flor seca se usa en infusiones en China.",
        "prune_when": "Después de floración (febrero-marzo) y poda fuerte en agosto si invade.",
        "prune_how": "Variable según ubicación. En techos y pérgolas: severa (40%) en agosto.",
        "water": "Medio. 2×/semana en verano, semanal el resto.",
        "light": "Sol o sombra parcial",
        "tags": ["exotica", "trepadora", "ornamental", "perfume", "polinizadores"],
        "loc_photo": "FondoCasa_FrenteDormitorio.jpg",
        "main_photo": "PXL_20260428_130124805_MP.webp",
        "flowering": [10, 11, 12, 1],
        "fruiting": [],
        "pruning": [2, 3, 8],
        "urgency": None,
    },
    {
        "id_codes": ["B-4"], "zone": "fondo",
        "common": "Hibisco / Rosa china",
        "charrua": "",
        "sci": "Hibiscus rosa-sinensis",
        "other_names": "Cucarda, pavonia, flor de Jamaica",
        "desc": "Arbusto perenne de gran porte con flores rojo-naranja espectaculares de 10-15cm. Cada flor dura un solo día pero produce muchas en sucesión.",
        "type": "perenne",
        "fun_fact": "Es la flor nacional de Malasia, Corea del Sur y Hawái. En Asia las mujeres las usan en el pelo: izquierda = soltera, derecha = casada. En Jamaica preparan té con sus pétalos secos (agua de Jamaica).",
        "prune_when": "Agosto-septiembre (antes del brote). Sensible al frío extremo.",
        "prune_how": "Moderada (25-30%). Eliminar madera vieja y ramas débiles.",
        "water": "Alto. 3×/semana en verano, 2×/semana en primavera-otoño.",
        "light": "Pleno sol a sombra ligera",
        "tags": ["exotica", "ornamental", "polinizadores"],
        "loc_photo": "FondoCasa_FrenteCocina.jpg",
        "main_photo": "PXL_20260428_130004297_MP.webp",
        "flowering": [10, 11, 12, 1, 2, 3, 4],
        "fruiting": [],
        "pruning": [8, 9],
        "urgency": None,
    },
    {
        "id_codes": ["B-5a", "B-5b"], "zone": "fondo",
        "common": "Hortensia",
        "charrua": "",
        "sci": "Hydrangea macrophylla",
        "other_names": "Tetilla, hortensia común",
        "desc": "Arbusto caduco/semi-caduco con grandes inflorescencias globulares en primavera-verano. El color depende del pH del suelo: ÁCIDO = azul, NEUTRO/ALCALINO = rosa.",
        "type": "caduco",
        "fun_fact": "Para que las flores salgan azules: enterrar 3-5 clavos oxidados o enterrar borra de café. Para rosa: agregar cal. Es la única planta que cambia de color según lo que coma del suelo.",
        "prune_when": "Febrero-marzo (después de floración) — IMPORTANTE: solo cortar tallos florecidos, NO los nuevos brotes.",
        "prune_how": "Selectiva. Cortar 1/3 de tallos viejos a ras del suelo para renovar.",
        "water": "Alto. 'Hydrangea' = sed de agua. 3-4×/semana en verano. Mulch grueso en verano.",
        "light": "Sombra parcial — sol de mañana, sombra de tarde",
        "tags": ["exotica", "ornamental", "maceta"],
        "loc_photo": "FondoCasa_FrenteCocina.jpg",
        "main_photo": "PXL_20260428_130026865_MP.webp",
        "flowering": [10, 11, 12, 1, 2],
        "fruiting": [],
        "pruning": [2, 3],
        "urgency": {"priority": "alta", "action": "Trasplantar a maceta más grande o tierra (las macetas chicas las hacen sufrir)", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-6"], "zone": "fondo",
        "common": "Esparraguera cola de zorro",
        "charrua": "",
        "sci": "Asparagus densiflorus 'Myers'",
        "other_names": "Foxtail fern, espárrago de adorno",
        "desc": "No es un helecho sino un asparagus (pariente del espárrago de comer). Tiene 'colas' verticales densas de aspecto plumoso. Muy resistente.",
        "type": "perenne",
        "fun_fact": "Aunque parece helecho NO LO ES: tiene flores blancas pequeñas y bayas rojas (que son tóxicas). Las 'hojas' son en realidad cladodios — tallos modificados.",
        "prune_when": "Otoño (mayo-junio). Cortar 'colas' viejas amarillas a ras.",
        "prune_how": "Selectiva. Eliminar lo seco, conservar lo verde.",
        "water": "Medio-bajo. 2×/semana en verano, semanal el resto.",
        "light": "Sol parcial a sombra",
        "tags": ["exotica", "maceta", "ornamental"],
        "loc_photo": "FondoCasa_FrenteCocina.jpg",
        "main_photo": "PXL_20260428_130020953_MP.webp",
        "flowering": [10, 11, 12],
        "fruiting": [],
        "pruning": [5, 6],
        "urgency": None,
    },
    {
        "id_codes": ["B-7", "B-11", "B-31", "B-33"], "zone": "fondo",
        "common": "Azarero / Pitósporo",
        "charrua": "",
        "sci": "Pittosporum tobira",
        "other_names": "Azahar de la China, pitósporo de Tobira",
        "desc": "Arbusto perenne muy usado como cerco en Uruguay. Flores blanco-cremosas perfumadísimas (huelen a azahar de naranjo) en octubre-noviembre. Frutos amarillos pequeños en otoño.",
        "type": "perenne",
        "fun_fact": "Su perfume tiene compuestos parecidos al azahar — los romanos hacían perfumes con plantas similares. En Japón se usa en bonsái porque tolera podas extremas.",
        "prune_when": "Mayo-junio (post-floración) y agosto si está muy denso.",
        "prune_how": "Moderada (20-30%). Recorte de cerco frecuente. Tolera podas severas.",
        "water": "Bajo. Semanal en verano, casi nada el resto. Tolera sequía.",
        "light": "Sol o sombra parcial",
        "tags": ["exotica", "perfume", "cerco-vivo", "polinizadores"],
        "loc_photo": "FondoCasa_VecinoFondo.jpg",
        "main_photo": "PXL_20260428_130248394_MP.webp",
        "flowering": [10, 11],
        "fruiting": [3, 4, 5],
        "pruning": [5, 6, 8],
        "urgency": None,
    },
    {
        "id_codes": ["B-8", "B-21", "B-28"], "zone": "fondo",
        "common": "Palmera pindó",
        "charrua": "Pindó (guaraní) / Mbocayá",
        "sci": "Syagrus romanzoffiana",
        "other_names": "Palmera reina, palmera de Romanzoff, jeriva",
        "desc": "Palmera NATIVA de hasta 20m, hojas pinadas elegantes hasta 4m. Frutos amarillo-anaranjados ovalados en racimos largos, comestibles y muy buscados por aves.",
        "type": "perenne",
        "fun_fact": "Su nombre 'romanzoffiana' es por el conde ruso Romanzoff que financió la expedición de Chamisso a América (1815-18). El fruto se chupaba como golosina natural por niños guaraníes — sabor a coco-banana.",
        "prune_when": "Cualquier época. Solo limpieza.",
        "prune_how": "Mínima. Solo cortar hojas amarillas o secas a ras del tronco. NUNCA podar las verdes.",
        "water": "Bajo. Una vez establecida, casi nada.",
        "light": "Pleno sol",
        "tags": ["nativa", "ornamental", "aves", "frutal"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "PXL_20260426_194320163_MP.webp",
        "flowering": [11, 12, 1],
        "fruiting": [3, 4, 5, 6, 7],
        "pruning": [6, 7],
        "urgency": None,
    },
    {
        "id_codes": ["B-9"], "zone": "fondo",
        "common": "Crespón / Mirto de crepe",
        "charrua": "",
        "sci": "Lagerstroemia indica (a confirmar)",
        "other_names": "Júpiter, espumilla, árbol de Júpiter",
        "desc": "Arbusto-árbol caduco con flores en panículas rosadas, fucsia, blancas o violáceas en pleno verano. Corteza exfoliante color canela espectacular en invierno.",
        "type": "caduco",
        "fun_fact": "Su nombre conmemora a Magnus von Lagerström, comerciante sueco amigo de Linneo que le mandaba plantas exóticas desde sus viajes. Las flores 'arrugadas' parecen hechas de papel crepé — de ahí 'crespón'.",
        "prune_when": "Junio-julio (invierno). Florece en madera nueva del año.",
        "prune_how": "Severa (50-70%) — 'crepe murder' es un mito: tolera podas drásticas y florece más.",
        "water": "Medio-bajo. Semanal en verano.",
        "light": "Pleno sol",
        "tags": ["exotica", "ornamental", "polinizadores"],
        "loc_photo": "FondoCasa_FrenteCocina.jpg",
        "main_photo": "b9.jpg",
        "flowering": [12, 1, 2, 3],
        "fruiting": [],
        "pruning": [6, 7],
        "urgency": {"priority": "alta", "action": "Poda invernal severa", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-10", "B-19"], "zone": "fondo",
        "common": "Lavanda",
        "charrua": "",
        "sci": "Lavandula dentata",
        "other_names": "Espliego, alhucema, lavanda de hoja dentada",
        "desc": "Aromática perenne de hojas grises dentadas y espigas violáceas. La especie *dentata* florece más tiempo que *angustifolia* (casi todo el año en Uruguay).",
        "type": "perenne",
        "fun_fact": "Romanos la echaban al baño público — de ahí su nombre (lat. 'lavare' = lavar). Su aceite esencial relaja por aromaterapia comprobada. Una bolsita de lavanda seca en el cajón ahuyenta polillas.",
        "prune_when": "Marzo-abril (post-floración principal) y agosto.",
        "prune_how": "Ligera (15-20%). NUNCA cortar madera vieja sin hojas — no rebrota desde madera vieja.",
        "water": "Muy bajo. Cada 10 días en verano, casi nada el resto. Odia tener pies mojados.",
        "light": "Pleno sol",
        "tags": ["exotica", "aromatica", "polinizadores", "abejas", "mariposas"],
        "loc_photo": "FondoCasa_FrenteCocina.jpg",
        "main_photo": "PXL_20260428_130145017_MP.webp",
        "flowering": [9, 10, 11, 12, 1, 2, 3, 4, 5],
        "fruiting": [],
        "pruning": [3, 4, 8],
        "urgency": None,
    },
    {
        "id_codes": ["B-12", "B-17"], "zone": "fondo",
        "common": "Cinta / Lazo de amor",
        "charrua": "",
        "sci": "Chlorophytum comosum",
        "other_names": "Mala madre, lengua de vaca, planta araña",
        "desc": "Hierba perenne en mata, hojas largas listadas verde-blanco. Produce 'hijos' colgantes que se pueden trasplantar (de ahí 'mala madre' — los echa de casa).",
        "type": "perenne",
        "fun_fact": "La NASA la incluyó en su lista de plantas que purifican el aire interior — absorbe formaldehído, xileno y monóxido de carbono. Una planta limpia ~10m². Es de las más fáciles de cultivar.",
        "prune_when": "Cualquier época. Cortar hojas amarillas y propagar 'hijos'.",
        "prune_how": "Selectiva. Eliminar hojas viejas o secas. Reproducir hijos en agua.",
        "water": "Medio. 2×/semana en verano, semanal el resto.",
        "light": "Sombra parcial a luz indirecta",
        "tags": ["exotica", "maceta", "interior", "purificadora"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "PXL_20260428_130332242_MP.webp",
        "flowering": [10, 11, 12, 1],
        "fruiting": [],
        "pruning": [],
        "urgency": None,
    },
    {
        "id_codes": ["B-13"], "zone": "fondo",
        "common": "Clivia / Lirio del Cabo",
        "charrua": "",
        "sci": "Clivia miniata (a confirmar)",
        "other_names": "Lirio amarillo, lirio del Cabo",
        "desc": "Bulbosa perenne de hojas largas en abanico. Floración espectacular en septiembre-octubre: umbelas de flores naranja-rojizas tipo trompeta. Tolera mucha sombra.",
        "type": "perenne",
        "fun_fact": "Su nombre honra a Charlotte Clive, duquesa de Northumberland (siglo XIX), primera en florecerla en cultivo en Inglaterra. Una clivia bien cuidada puede vivir 100 años — hay ejemplares en jardines reales que datan de 1830.",
        "prune_when": "No requiere poda. Solo cortar varas florales secas.",
        "prune_how": "Mínima. Eliminar hojas amarillas en su base.",
        "water": "Bajo en invierno (forzar sequía estimula floración), medio en primavera-verano.",
        "light": "Sombra a sombra parcial",
        "tags": ["exotica", "ornamental", "sombra", "maceta"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "b13.jpg",
        "flowering": [9, 10, 11],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "media", "action": "Trasplantar bulbo (está saliendo de la maceta) o agregar tierra", "when": "Junio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-14"], "zone": "fondo",
        "common": "Pendiente identificación (¿lapachillo?)",
        "charrua": "",
        "sci": "(a determinar)",
        "other_names": "—",
        "desc": "Árbol grande hojas verdes oscuras a la izquierda de la pileta. Falta más fotos.",
        "type": "perenne",
        "fun_fact": "—",
        "prune_when": "A determinar tras identificación",
        "prune_how": "—",
        "water": "Medio (provisional)",
        "light": "Pleno sol (provisional)",
        "tags": ["pendiente"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "PXL_20260428_130305782_MP.webp",
        "flowering": [],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "baja", "action": "Sacar foto en floración para identificar", "when": "Primavera-verano 2026", "due_month": 10, "due_year": 2026},
    },
    {
        "id_codes": ["B-15"], "zone": "fondo",
        "common": "Vegetación pendiente sobre galpón",
        "charrua": "",
        "sci": "(a determinar)",
        "other_names": "—",
        "desc": "Vegetación sobre el galpón del fondo. Difícil identificar de lejos.",
        "type": "perenne",
        "fun_fact": "—",
        "prune_when": "A determinar",
        "prune_how": "—",
        "water": "—",
        "light": "—",
        "tags": ["pendiente"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "PXL_20260428_130401399_MP.webp",
        "flowering": [],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "baja", "action": "Acercarse y sacar foto closeup", "when": "Cuando puedan", "due_month": 8, "due_year": 2026},
    },
    {
        "id_codes": ["B-16"], "zone": "fondo",
        "common": "Anacahuita",
        "charrua": "Anacahuita (charrúa) / Aratiku-pitá",
        "sci": "Schinus longifolius",
        "other_names": "Molle blanco, molle anacahuita",
        "desc": "Árbol NATIVO uruguayo de copa redonda y hojas perennes alargadas. Frutos pequeños rosados en racimos. Pariente del aguaribay pero hojas más finas y largas.",
        "type": "perenne",
        "fun_fact": "Es uno de los árboles más simbólicos del Uruguay — protegido por ley nacional desde 1986. Su madera dura era usada por los charrúas para hacer arcos y rejas. Florece en racimos blanco-amarillentos discretos pero muy melíferos.",
        "prune_when": "Junio-julio (invierno). Solo formación.",
        "prune_how": "Mínima (5-15%). Eliminar ramas secas y cruzadas.",
        "water": "Muy bajo. Tolera sequía extrema.",
        "light": "Pleno sol",
        "tags": ["nativa", "polinizadores", "aves", "ornamental"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "PXL_20260428_130510131_MP.webp",
        "flowering": [10, 11, 12],
        "fruiting": [3, 4, 5],
        "pruning": [6, 7],
        "urgency": None,
    },
    {
        "id_codes": ["B-18"], "zone": "fondo",
        "common": "Rosa de Siria / Althea",
        "charrua": "",
        "sci": "Hibiscus syriacus",
        "other_names": "Hibiscus de Siria, althea, rose of Sharon",
        "desc": "Arbusto caduco con grandes flores acampanadas blancas, rosadas, violáceas o azules en verano. Más rústico que el hibisco rojo — soporta heladas.",
        "type": "caduco",
        "fun_fact": "Es la flor nacional de Corea del Sur — aparece en su escudo y su himno. Cada flor dura un solo día pero la planta produce cientos en sucesión. La biblia hebrea menciona la 'rose of Sharon' (Rosa de Saron).",
        "prune_when": "Junio-julio (invierno, en plena dormancia).",
        "prune_how": "Severa (40-50%). Reducir ramas a 2-3 yemas. Florece en madera nueva.",
        "water": "Medio. Semanal en verano.",
        "light": "Pleno sol",
        "tags": ["exotica", "ornamental", "polinizadores", "rusticidad"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "b18.jpg",
        "flowering": [12, 1, 2, 3],
        "fruiting": [],
        "pruning": [6, 7],
        "urgency": {"priority": "alta", "action": "Poda invernal severa", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-20"], "zone": "fondo",
        "common": "Arbusto caduco a identificar",
        "charrua": "",
        "sci": "(esperar floración primaveral)",
        "other_names": "—",
        "desc": "Arbusto en tambor casi pelado en mayo. Imposible identificar sin hojas/flores. Provisional cerrado.",
        "type": "caduco",
        "fun_fact": "—",
        "prune_when": "A determinar",
        "prune_how": "—",
        "water": "Bajo (en reposo invernal)",
        "light": "Sol",
        "tags": ["pendiente"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "b20.jpg",
        "flowering": [],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "baja", "action": "Sacar foto en septiembre-octubre cuando brote", "when": "Primavera 2026", "due_month": 9, "due_year": 2026},
    },
    {
        "id_codes": ["B-22"], "zone": "fondo",
        "common": "Palta uruguaya",
        "charrua": "",
        "sci": "Persea americana",
        "other_names": "Aguacate criollo, palta verde",
        "desc": "Árbol grande perenne con frutos grandes verdes. La 'palta uruguaya' tradicional es de piel lisa fina, pulpa cremosa y semilla grande.",
        "type": "perenne",
        "fun_fact": "La palta es un fruto evolutivamente solitario: su semilla gigante estaba diseñada para ser tragada por gigantosloth (perezosos gigantes) que se extinguieron hace 13,000 años. Sobrevivió gracias al cultivo humano.",
        "prune_when": "Septiembre (inicio primavera) tras cosecha.",
        "prune_how": "Ligera (15-20%). Eliminar ramas chupón y guías altas para mantener cosechable.",
        "water": "Alto. 3-4×/semana en verano. Sufre con sequía.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal"],
        "loc_photo": "FondoCasa_FrentePiscina.jpg",
        "main_photo": "PXL_20260428_130522139_MP.webp",
        "flowering": [9, 10, 11],
        "fruiting": [4, 5, 6, 7],
        "pruning": [9, 10],
        "urgency": None,
    },
    {
        "id_codes": ["B-23"], "zone": "fondo",
        "common": "Limonero",
        "charrua": "",
        "sci": "Citrus × limon",
        "other_names": "Limón eureka, limón común",
        "desc": "Cítrico perenne que produce limones casi todo el año en Uruguay. Flores blancas perfumadas (azahar) varias veces al año.",
        "type": "perenne",
        "fun_fact": "El limonero NO existe en estado silvestre — es híbrido de cidro × naranja amarga. Se originó en India hace ~2500 años. Cada limón viene de una flor única, no de racimos. La cáscara tiene 4× más vitamina C que el jugo.",
        "prune_when": "Agosto-septiembre (post-cosecha mayor) y febrero (limpieza).",
        "prune_how": "Moderada (20-30%). Eliminar chupones, ramas secas y ramas que se cruzan. Mantener centro abierto.",
        "water": "Alto. 3×/semana en verano, 2×/semana primavera-otoño.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal", "perfume"],
        "loc_photo": "FondoCasa_Cancha_Padel.jpg",
        "main_photo": "PXL_20260428_130529587_MP.webp",
        "flowering": [9, 10, 11, 3, 4],
        "fruiting": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "pruning": [8, 9, 2],
        "urgency": None,
    },
    {
        "id_codes": ["B-24"], "zone": "fondo",
        "common": "Mandarina criolla",
        "charrua": "",
        "sci": "Citrus reticulata",
        "other_names": "Mandarino, mandarina común",
        "desc": "Cítrico perenne de fruto pequeño dulce con cáscara que se separa fácilmente. Florece en primavera, cosecha en otoño-invierno.",
        "type": "perenne",
        "fun_fact": "Su nombre viene de los 'mandarines' — funcionarios de la China imperial que vestían túnicas anaranjadas. Es el cítrico más antiguo conocido (3000 a.C.) — el padre de naranjas y limones modernos.",
        "prune_when": "Agosto-septiembre (post-cosecha) y limpieza en febrero.",
        "prune_how": "Moderada (20%). Eliminar ramas internas para luz al centro.",
        "water": "Alto en floración y fructificación.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal"],
        "loc_photo": "FondoCasa_Cancha_Padel.jpg",
        "main_photo": "PXL_20260428_130827515_MP.webp",
        "flowering": [9, 10, 11],
        "fruiting": [4, 5, 6, 7, 8],
        "pruning": [8, 9, 2],
        "urgency": None,
    },
    {
        "id_codes": ["B-25"], "zone": "fondo",
        "common": "Gardenia / Jazmín del Cabo",
        "charrua": "",
        "sci": "Gardenia jasminoides (a confirmar)",
        "other_names": "Jazmín del cabo, gardenia común",
        "desc": "Arbusto perenne de hojas brillantes y flores blancas dobles intensamente perfumadas en primavera-verano.",
        "type": "perenne",
        "fun_fact": "Su perfume es uno de los más caros para extraer — hace falta 600 kg de flores para 1L de aceite esencial. Coco Chanel obsesionada con la gardenia, la incorporó al Chanel Nº 22. Las flores se ponen amarillas si el suelo es alcalino — necesita pH ácido.",
        "prune_when": "Después de floración (marzo-abril).",
        "prune_how": "Ligera (15-20%). Eliminar flores marchitas y ramas débiles.",
        "water": "Medio-alto. 2-3×/semana en verano. Adora humedad.",
        "light": "Sol parcial — sol mañana, sombra tarde",
        "tags": ["exotica", "perfume", "ornamental"],
        "loc_photo": "FondoCasa_Cancha_Padel.jpg",
        "main_photo": "b25.jpg",
        "flowering": [10, 11, 12, 1, 2],
        "fruiting": [],
        "pruning": [3, 4],
        "urgency": None,
    },
    {
        "id_codes": ["B-26"], "zone": "fondo",
        "common": "Romero",
        "charrua": "",
        "sci": "Salvia rosmarinus",
        "other_names": "Rosmarinus officinalis (nombre antiguo)",
        "desc": "Aromática perenne de hojas tipo aguja muy aromáticas. Flores azul-lila pequeñas en invierno-primavera. Imprescindible en cocina mediterránea.",
        "type": "perenne",
        "fun_fact": "Su nombre latino 'rosmarinus' = 'rocío del mar' (crece en acantilados mediterráneos). Estudios universitarios mostraron que oler romero antes de un examen mejora la memoria 15%. Antiguo símbolo de la fidelidad — los novios llevaban una rama el día de la boda.",
        "prune_when": "Octubre-noviembre (post-floración) y poda ligera en febrero.",
        "prune_how": "Moderada (25-30%). NUNCA cortar madera vieja sin hojas. Reformar arbusto.",
        "water": "Muy bajo. Tolera sequía extrema. Cada 10-14 días en verano.",
        "light": "Pleno sol",
        "tags": ["exotica", "aromatica", "comestible", "polinizadores", "abejas"],
        "loc_photo": "FondoCasa_Cancha_Padel.jpg",
        "main_photo": "PXL_20260428_130842254_MP.webp",
        "flowering": [6, 7, 8, 9, 10],
        "fruiting": [],
        "pruning": [10, 11, 2],
        "urgency": None,
    },
    {
        "id_codes": ["B-27"], "zone": "fondo",
        "common": "Arbusto colgante pendiente",
        "charrua": "",
        "sci": "(a determinar)",
        "other_names": "—",
        "desc": "Arbusto colgante con flores secas. Pendiente más fotos.",
        "type": "perenne",
        "fun_fact": "—",
        "prune_when": "A determinar",
        "prune_how": "—",
        "water": "Medio (provisional)",
        "light": "Sol parcial (provisional)",
        "tags": ["pendiente"],
        "loc_photo": "FondoCasa_Cancha_Padel.jpg",
        "main_photo": "PXL_20260428_130857270_MP.webp",
        "flowering": [],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "baja", "action": "Sacar foto en floración", "when": "Primavera 2026", "due_month": 10, "due_year": 2026},
    },
    {
        "id_codes": ["B-29"], "zone": "fondo",
        "common": "Lantana / Camará",
        "charrua": "Camará / Ka'a-pondá (guaraní)",
        "sci": "Lantana camara",
        "other_names": "Bandera española, siete colores",
        "desc": "Arbusto NATIVO de Sudamérica con flores en pequeñas inflorescencias multicolores (amarillo, naranja, rojo, rosa). Atrae mariposas y picaflores. ¡Las bayas son tóxicas!",
        "type": "semi-perenne",
        "fun_fact": "Las flores cambian de color a medida que envejecen — recién abiertas amarillo, luego naranja, finalmente rojo. Esto le indica a los polinizadores cuáles son las flores 'frescas'. Los charrúas la usaban como repelente: encendían sus hojas para ahuyentar mosquitos.",
        "prune_when": "Junio-julio (invierno, fuerte) y enero (limpieza).",
        "prune_how": "Severa (50-70%). Cortar a 30cm del suelo en invierno. Florece en madera nueva.",
        "water": "Bajo. Tolera sequía. Riego semanal en verano.",
        "light": "Pleno sol",
        "tags": ["nativa", "polinizadores", "mariposas", "picaflor", "ornamental"],
        "loc_photo": "FondoCasa_VecinoFondo.jpg",
        "main_photo": "PXL_20260428_130908091_MP.webp",
        "flowering": [10, 11, 12, 1, 2, 3, 4, 5],
        "fruiting": [],
        "pruning": [6, 7, 1],
        "urgency": {"priority": "media", "action": "Poda fuerte de invierno", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-30", "B-35"], "zone": "fondo",
        "common": "Durazno",
        "charrua": "",
        "sci": "Prunus persica",
        "other_names": "Melocotonero, durazno blanco/amarillo",
        "desc": "Frutal caduco con flores rosadas a fin de invierno (agosto) antes que las hojas. Cosecha de duraznos en diciembre-enero según variedad.",
        "type": "caduco",
        "fun_fact": "Aunque 'persica' = de Persia, el durazno es originario de China — 8000 años de cultivo. Llegó a Europa por la ruta de la seda y pareció persa a los romanos. La piel aterciopelada es defensa contra hongos.",
        "prune_when": "Junio-julio (invierno, dormancia plena). Poda CRÍTICA — sin podar fructifica mal.",
        "prune_how": "Severa (40-50%). Forma copa abierta o vaso. Cortar 3-4 ramas principales y eliminar lo viejo.",
        "water": "Alto en floración y fructificación. Cuidar pies para evitar hongos.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal"],
        "loc_photo": "FondoCasa_VecinoFondo.jpg",
        "main_photo": "b30.jpg",
        "flowering": [8, 9],
        "fruiting": [12, 1, 2],
        "pruning": [6, 7],
        "urgency": {"priority": "alta", "action": "Poda invernal urgente — sin podar fructifica mal", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-32"], "zone": "fondo",
        "common": "Varitas peladas pendientes",
        "charrua": "",
        "sci": "(esperar primavera)",
        "other_names": "—",
        "desc": "Sin hojas. Falta brote primaveral.",
        "type": "caduco",
        "fun_fact": "—",
        "prune_when": "A determinar",
        "prune_how": "—",
        "water": "Bajo (en reposo)",
        "light": "Sol",
        "tags": ["pendiente"],
        "loc_photo": "FondoCasa_VecinoFondo.jpg",
        "main_photo": "PXL_20260428_130952009_MP.webp",
        "flowering": [],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "baja", "action": "Sacar foto en septiembre cuando brote", "when": "Primavera 2026", "due_month": 9, "due_year": 2026},
    },
    {
        "id_codes": ["B-34"], "zone": "fondo",
        "common": "Pendiente identificación",
        "charrua": "",
        "sci": "(a determinar)",
        "other_names": "—",
        "desc": "Falta más fotos.",
        "type": "perenne",
        "fun_fact": "—",
        "prune_when": "A determinar",
        "prune_how": "—",
        "water": "—",
        "light": "—",
        "tags": ["pendiente"],
        "loc_photo": "FondoCasa_VecinoFondo.jpg",
        "main_photo": "PXL_20260428_131001512_MP.jpg",
        "flowering": [],
        "fruiting": [],
        "pruning": [],
        "urgency": {"priority": "baja", "action": "Sacar foto closeup", "when": "Cuando puedan", "due_month": 8, "due_year": 2026},
    },
    {
        "id_codes": ["B-36"], "zone": "fondo",
        "common": "Palta Haas",
        "charrua": "",
        "sci": "Persea americana 'Hass'",
        "other_names": "Palta hass, aguacate hass",
        "desc": "Cultivar específico de palta — frutos pequeños-medianos con piel rugosa que se oscurece al madurar. Pulpa cremosa y rica en aceites. Más resistente al frío que la palta uruguaya.",
        "type": "perenne",
        "fun_fact": "TODAS las paltas Hass del mundo descienden de UN único árbol plantado por Rudolph Hass en 1926 en California. Se reproduce solo por injerto — no funciona por semilla. ~80% de la palta exportada mundialmente es Hass.",
        "prune_when": "Septiembre (inicio primavera).",
        "prune_how": "Ligera (15-20%). Mantener altura cosechable. Eliminar chupones del injerto.",
        "water": "Alto. 3-4×/semana en verano.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal"],
        "loc_photo": "FondoCasa_VecinoFondo.jpg",
        "main_photo": "FondoCasa_VecinoFondo.jpg",
        "flowering": [9, 10],
        "fruiting": [5, 6, 7, 8, 9, 10],
        "pruning": [9],
        "urgency": None,
    },
    {
        "id_codes": ["B-37"], "zone": "fondo",
        "common": "Liquidámbar",
        "charrua": "",
        "sci": "Liquidambar styraciflua",
        "other_names": "Liquidámbar americano, sweetgum, ocozol",
        "desc": "Árbol caduco majestuoso de copa cónica/redondeada. Hojas palmadas tipo arce que viran rojo-borgoña-amarillo en otoño. Frutos en bolas espinosas.",
        "type": "caduco",
        "fun_fact": "Su tronco produce un bálsamo aromático ('storax') usado durante 3000 años en perfumería e incienso — los mayas lo masticaban como goma de mascar y los aztecas lo ofrecían a sus dioses. Su nombre = 'ámbar líquido' por la resina.",
        "prune_when": "Junio-julio. Solo limpieza — no requiere poda fuerte.",
        "prune_how": "Mínima (5-10%). Eliminar ramas secas, cruzadas o mal posicionadas.",
        "water": "Medio. Bien establecido tolera bien la sequía.",
        "light": "Pleno sol (para máximo color otoñal)",
        "tags": ["exotica", "ornamental", "sombra"],
        "loc_photo": "FondoCasa_CuartoFondo.jpg",
        "main_photo": "PXL_20260426_194351840_MP.webp",
        "flowering": [10, 11],
        "fruiting": [3, 4, 5],
        "pruning": [6, 7],
        "urgency": None,
    },
    {
        "id_codes": ["B-38"], "zone": "fondo",
        "common": "Ciruela amarilla",
        "charrua": "",
        "sci": "Prunus salicina",
        "other_names": "Ciruelo japonés, ciruela claudia",
        "desc": "Frutal caduco con flores blancas en agosto y ciruelas amarillas/doradas en diciembre-enero.",
        "type": "caduco",
        "fun_fact": "Aunque se llama 'japonés', es de origen chino. Llegó a Japón en el siglo VIII y de ahí a EEUU/Europa. Las ciruelas amarillas tienen menos azúcar pero más vitamina C que las moradas.",
        "prune_when": "Junio-julio (invierno).",
        "prune_how": "Moderada (30%). Forma copa abierta. Eliminar madera de más de 4 años.",
        "water": "Medio-alto durante fructificación.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal"],
        "loc_photo": "FondoCasa_CuartoFondo.jpg",
        "main_photo": "PXL_20260428_130808343_MP.webp",
        "flowering": [8, 9],
        "fruiting": [12, 1, 2],
        "pruning": [6, 7],
        "urgency": {"priority": "alta", "action": "Poda invernal", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-39"], "zone": "fondo",
        "common": "Pera Williams",
        "charrua": "",
        "sci": "Pyrus communis 'Williams'",
        "other_names": "Pera Bartlett, pera de agua",
        "desc": "Frutal caduco con flores blancas en agosto-septiembre. Peras dulces, jugosas y aromáticas en febrero-marzo.",
        "type": "caduco",
        "fun_fact": "La cultivó por primera vez Stair en Inglaterra en 1765, comprada por Williams (de ahí el nombre). En EEUU se llama Bartlett porque Enoch Bartlett la introdujo allá sin saber que ya tenía nombre. La 'pera Williams' es la base de la mayoría de las peras industriales mundiales.",
        "prune_when": "Junio-julio (invierno).",
        "prune_how": "Moderada (25-35%). Eliminar chupones, ramas mal orientadas. Forma piramidal.",
        "water": "Medio-alto durante fructificación.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal"],
        "loc_photo": "FondoCasa_CuartoFondo.jpg",
        "main_photo": "PXL_20260428_130757603_MP.webp",
        "flowering": [8, 9],
        "fruiting": [2, 3],
        "pruning": [6, 7],
        "urgency": {"priority": "alta", "action": "Poda invernal", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
    {
        "id_codes": ["B-40"], "zone": "fondo",
        "common": "Madreselva china siempreverde",
        "charrua": "",
        "sci": "Lonicera nitida (a confirmar)",
        "other_names": "Boxleaf honeysuckle, madreselva enana",
        "desc": "Arbusto bajo perenne de hojas pequeñas ovaladas opuestas, brillantes. Flores blancas pequeñas, frutos violáceos. Excelente para cerco bajo o tapizante.",
        "type": "perenne",
        "fun_fact": "A pesar del nombre 'honeysuckle/madreselva', sus flores son insignificantes — se cultiva por el follaje. Los pájaros adoran sus bayas violáceas. Tolera podas extremas y se modela en topiaria.",
        "prune_when": "Cualquier época. Mejor en agosto y febrero.",
        "prune_how": "Moderada (20-30%). Tolera podas en cubos, esferas o topiaria.",
        "water": "Medio-bajo.",
        "light": "Sol o sombra parcial",
        "tags": ["exotica", "cerco-vivo", "aves"],
        "loc_photo": "",
        "main_photo": "PXL_20260428_130913516_MP.webp",
        "flowering": [11, 12],
        "fruiting": [3, 4],
        "pruning": [8, 2],
        "urgency": None,
    },
    {
        "id_codes": ["B-41"], "zone": "fondo",
        "common": "Caqui / Persimón",
        "charrua": "",
        "sci": "Diospyros kaki (a confirmar)",
        "other_names": "Kaki, palo santo, persimon",
        "desc": "Frutal caduco con hojas grandes ovaladas que viran amarillo-naranja en otoño. Frutos naranjas brillantes que quedan colgados después de la caída de hojas — espectacular.",
        "type": "caduco",
        "fun_fact": "Su nombre genérico 'Diospyros' = 'fruto de los dioses' en griego. En Japón es símbolo de longevidad — hay caquis de 600 años aún produciendo. El fruto inmaduro es astringente (alta cantidad de taninos) — hay que esperar hasta que se ponga blando.",
        "prune_when": "Junio-julio (invierno).",
        "prune_how": "Moderada (25-35%). Forma copa abierta. Cuidar el injerto los primeros años.",
        "water": "Medio. Importante en floración y cuajado.",
        "light": "Pleno sol",
        "tags": ["exotica", "frutal", "ornamental"],
        "loc_photo": "",
        "main_photo": "PXL_20260428_131121049_MP.webp",
        "flowering": [10, 11],
        "fruiting": [5, 6, 7],
        "pruning": [6, 7],
        "urgency": {"priority": "alta", "action": "Poda invernal de formación", "when": "Junio-julio 2026", "due_month": 6, "due_year": 2026},
    },
]
